export const GET_USERS_STARTED = 'GET_USERS_STARTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const INCREMENT_OFFSET = 'INCREMENT_OFFSET';

export const DELETE_USER = 'DELETE_USER';
export const FILTER_USERS = 'FILTER_USERS';
