export const FETCH_USERS = 'FETCH_USERS';
export const INCREMENT_OFFSET = 'INCREMENT_OFFSET';
export const INCREMENT_OFFSET_PENDING = 'INCREMENT_OFFSET_PENDING';
export const DELETE_USER = 'DELETE_USER';
export const FILTER_USERS = 'FILTER_USERS';

export type FETCH_USERS = 'FETCH_USERS';
export type INCREMENT_OFFSET = 'INCREMENT_OFFSET';
export type INCREMENT_OFFSET_PENDING = 'INCREMENT_OFFSET_PENDING';
export type DELETE_USER = 'DELETE_USER';
export type FILTER_USERS = 'FILTER_USERS';
